all: testytest

testytest:
	$ g++ -std=c++11 -o testytest flowersTest.cpp flowersStudent.cpp flowersExamples.cpp 

gradygrade:
	$ g++ -std=c++11 -o gradygrade flowersGrading.cpp flowersStudent.cpp flowersExamples.cpp 

clean: 
	rm -rf *.o testytest gradygrade
