all: testytest

testytest:
	$ g++ -std=c++11 -o testytest edenTest.cpp edenStudent.cpp 

gradygrade:
	$ g++ -std=c++11 -o gradygrade edenGrading.cpp edenStudent.cpp eden.h fraction.h 

clean: 
	rm -rf *.o testytest gradygrade
